### ISSUE TITLE
Clumps double XP

### ISSUE THREAD

**Issue by JoeSGT** [jaredlll08/Clumps#10]
Hello,

Forge: forge-1.12.2-14.23.1.2607
Clumps: 3.0.0

Hello i ran a test with and without Clumps 
i place down 56 RedStone Ores without Clumps i made exactly 9 levels 
with Clumps i made 13 levels it double it by 3 times when you include Fortune 3 or any one 
it double it even more 
can you possible fix this please and thanks

**Comment by JoeSGT** [comment]
https://github.com/jaredlll08/Clumps/blob/master/src/main/java/com/blamejared/clumps/entities/EntityXPOrbBig.java#L183-L189
It seem you are double it, is this intentional ?

**Comment by jaredlll08** [comment]
... that is for converting xp to durability for the repair enchantment, and uses the same values as vanilla.
As for the "doubling" of the XP, xp values range anywhere from 3-7 when vanilla generates them, you will never get the exact amount back

**Comment by JoeSGT** [comment]
but is there a way to disable this doubling?

**Comment by jaredlll08** [comment]
It Isn't doubling, it is simply the randomness that is applied to vanilla
XP orbs as well.
