### ISSUE TITLE
[1.18.2] Crash with new Clumps-forge-1.18.2-8.0.0+9.jar

### ISSUE THREAD

**Issue by gchpaco** [jaredlll08/Clumps#100]
[crash-2022-06-15_17.13.31-server.txt](https://github.com/jaredlll08/Clumps/files/8913541/crash-2022-06-15_17.13.31-server.txt)

This happened after I killed a crocodile.  It does not directly target clumps, but clumps modifies this stuff.

**Comment by jaredlll08** [comment]
Ah sorry about that, update and it should be fixed
