### ISSUE TITLE
doesnt work??

### ISSUE THREAD

**Issue by firestorm2039** [jaredlll08/Clumps#101]
for some reason this this isnt working, it is still leaving multiple orbs. this used to work on 1.16, but now i have upgraded it to 1.18.1 its not?
i have downloaded the 1.18.1 version of this mod yes

**Comment by jaredlll08** [comment]
Going to need a log file and more info, like what version of Clumps are you using? are you on Forge or Fabric?

**Comment by firestorm2039** [comment]
[latest.log](https://github.com/jaredlll08/Clumps/files/9035223/latest.log)

Logs attached (Latest)
i am using [Clumps-forge-1.18.1-8.0.0+5.jar (most recently updated 1.18.1 version), i am also using the forge version.

**Comment by jaredlll08** [comment]
Can you please show a screenshot of orbs being close together but not clumping together?

**Comment by firestorm2039** [comment]
![2022-07-03_19 46 03](https://user-images.githubusercontent.com/75093996/177053252-5a122f53-fb8e-44f1-ab60-9ec9d3953263.png)
![2022-07-03_19 46 59](https://user-images.githubusercontent.com/75093996/177053254-6df6c3c1-6b87-411b-a9fe-ffbb58fd97c1.png)
![2022-07-03_19 47 02](https://user-images.githubusercontent.com/75093996/177053257-3f19c0d4-5793-4af3-b4ed-b6d780ad79d4.png)
![2022-07-03_19 47 15](https://user-images.githubusercontent.com/75093996/177053259-794af95e-afb8-4f36-9afc-a0e4b6b3e167.png)
![2022-07-03_19 47 30](https://user-images.githubusercontent.com/75093996/177053264-c04827b7-e3a7-497b-9fff-e14e80d9f866.png)

**Comment by jaredlll08** [comment]
Those orbs are nowhere near close enough to each other to merge.

Prior to 1.17, the area was a 2x2x2 radius around the orb, so it would look in:
```
XXXXX
XXXXX
XXOXX
XXXXX
XXXXX
```
With X being the space to look and O being the orb

With 1.17, vanilla added their own xp merging (although at a *much* rarer chance than Clumps), and they used a 1x1x1 radius, like so:
```
XXX
XOX
XXX
```


I think having the same range as vanilla is better than the old range, so I will not be changing it.

**Comment by firestorm2039** [comment]
if 1 block away isn't close enough, i dont think there is any point me having this mod then.

**Comment by jaredlll08** [comment]
1 block away is close enough and in your image those orbs aren't 1 block away, they are *maybe* 1.5 to 2 blocks away.

Having more range will also allow orbs to clump through walls, which could cause issues.

I don't care if you use the mod or not, but by not using it, you're still going to deal with vanilla's own 1 block distance as well as their stricter merging criteria.
