### ISSUE TITLE
[Compatability issue]

### ISSUE THREAD

**Issue by BioTechproject27** [jaredlll08/Clumps#102]
Clumps has issues together with mcda's (minecraft dungeons armors) "bag of souls" enchantment, which increases picked up orb value.
With Clumps the value is not changed, but the orbs are still picked up.

**Comment by jaredlll08** [comment]
There isn't anything that I can do on *just* my side to fix this, I did comment on an issue report on their side (https://github.com/chronosacaria/MCDungeonsArmors/issues/47) with a possible solution if they are interested though.
