### ISSUE TITLE
Clumped Orbs from Trading give 0 EXP

### ISSUE THREAD

**Issue by MT729** [jaredlll08/Clumps#105]
Purchased some items for comparison before and after. This is from the Fabric version of the mod.

![javaw_0KfweQf66T](https://user-images.githubusercontent.com/94226992/179890100-1ec76a3a-1b69-4c02-a12e-fd134ff58549.jpg)
![javaw_e3QXl8tDs3](https://user-images.githubusercontent.com/94226992/179890088-8ee92cf8-1d7f-4bb3-8c76-0c4ff7ff2a95.jpg)

**Comment by jmadarg** [comment]
Having the same issue here, but with xp of any source

**Comment by jaredlll08** [comment]
Mc version? Forge or Fabric? Clumps version?
