### ISSUE TITLE
Mending on a tool causes an internal server error

### ISSUE THREAD

**Issue by ThatsAsh** [jaredlll08/Clumps#106]
We have clumps and a few other mods on a server, while at my mob farm healing my pickaxe which has mending on it, I had gotten an internal server error, and on the server it printed out this error many times

at net.minecraft.world.entity.ExperienceOrb.m_147092_(ExperienceOrb.java:228) ~[server-1.18.2-20220404.173914-srg.jar%23112!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:clumps.mixins.json:ExperienceOrbAccess,

This repeats several times. I am unsure of the true cause of it.

**Comment by jaredlll08** [comment]
Do you have forbidden arcanus installed?

I need the full log file please

**Comment by ThatsAsh** [comment]
Yes we do have that mod installed. The issue starts at line 1082

[2022-07-22-1.log](https://github.com/jaredlll08/Clumps/files/9170059/2022-07-22-1.log)

**Comment by jaredlll08** [comment]
What version of forbidden arcanus and valhelsia core are you using?

**Comment by jaredlll08** [comment]
I believe this is an issue with Forbidden Arcanus, I'm not sure why clumps causes the crash specifically, but they have some very inefficient code in a method that is called frequently.

They already have an issue open for it here:
https://github.com/stal111/Forbidden-Arcanus/issues/271

**Comment by jaredlll08** [comment]
This was an issue with clumps, more info here https://github.com/jaredlll08/Clumps/issues/107

**Comment by ThatsAsh** [comment]
We're using the latest version of both

**Comment by jaredlll08** [comment]
Upload your latest.log file then please.
