### ISSUE TITLE
Clumps deletes entities that aren't xp orbs

### ISSUE THREAD

**Issue by DaedalusGame** [jaredlll08/Clumps#11]
https://github.com/jaredlll08/Clumps/blob/master/src/main/java/com/blamejared/clumps/events/CommonEventHandler.java#L16
Checks for subclasses of xp aswell as xp itself, so BWA spirits (not xp) are also summarized (into xp)
Thanks in advance for looking into this

**Comment by jaredlll08** [comment]
Are spirits considered XP orbs?

**Comment by darkhax** [comment]
@DaedalusGame This seems like an issue with your spirits, if they're not EXP orbs, don't extend the EXP orb entity class. For example, your spirits will have issues with the EXP Monolith in Dark Utilities, or any other block/thing that works with EXP.

**Comment by DaedalusGame** [comment]
which means that i'll end up duplicating a load of functionality but i can probably do that begrudgingly

**Comment by jaredlll08** [comment]
@DaedalusGame Don't blame us for your laziness. your code would break with:
Darkutils EXP monolith
Actually additions xp solidifier
Mob Grinding Utils item hopper (or whatever the name is, it sucks up experience)
Any mod that expects EntityXPOrb to be used for, well you know, Experience Orbs.
