### ISSUE TITLE
Double XP Gains

### ISSUE THREAD

**Issue by HadrianFaerwald** [jaredlll08/Clumps#110]
I had just finished setting up a skeleton spawner mob farm, and when it was all said and done, I think I was around level 20-30 range, and I killed my group of skeletons sitting there, and I went up to around level 60.

I did some testing, turned Clumps off and waited 10 minutes, then killed my group from 0 XP/Levels and I got around 24 levels, turned Clumps back on, waited the 10 minutes, set my XP back to 0, and I got over 50.

I don't know what's causing this, but it's a huge problem cause it's waaaaay too much XP for something like this.

I hope this can get fixed and isn't an "intended feature" of this plugin.

Thank you!

**Comment by jaredlll08** [comment]
Clumps gives the exact same experience values that vanilla does, https://youtu.be/_0Bo2yb63Eo

Maybe you have another mod messing with things? Can you reproduce with just clumps?

What mc version?
What clumps version?
ModLoader version?

**Comment by HadrianFaerwald** [comment]
I tested it with and without the extra mods, it's just Clumps that is messing with it

MC Version: 1.19.2
Clumps Version: 1.19.2-9.0.0+11
And the server I have it on is running the latest version of Fabric, I don't know what version that is specifically. (MCProhosting)

**Comment by HadrianFaerwald** [comment]
Doing additional tests
Please hold.

**Comment by HadrianFaerwald** [comment]
Huh, interesting...

I must have missed the Carpet mod during my tests, for some reason the xpNoCooldown command was for some reason giving double xp, sorry bout that! Though a good thing to know for people later on.

No idea why it does that, but disabling that is the fix!
Sorry about the hassle D:
Have a good night/day!
