### ISSUE TITLE
glitched LVL

### ISSUE THREAD

**Issue by naecker21** [jaredlll08/Clumps#114]
I was testing a Fortress farm for a few hours to make shure that it is working properly. I ended testing at about level 700. after that i saw a leftover xp orb in the killing chamber and collected it in creative when switching i was meat with a level near the integrall limit 21.000 something.

So is it intentionally that this could happen or could it be that the game didnt calculate properly

**Comment by jaredlll08** [comment]
MC Version?
Modloader Version?
Clumps Version?
Any other mods like Carpet or similar that messes with experience as well?

**Comment by naecker21** [comment]
MC 1.19.e
Fabric loader 0.14.11
Clumps version 9.0.0+16
And there shouldn't be any mods that messes with XP

**Comment by jaredlll08** [comment]
> 1.19.e

What is `.e`?

And can I get a mod list please

**Comment by naecker21** [comment]
1.19.3 
Architectury
Bobby
Carpet Extra
Carpet Mod
Carpet TIS Addition
Carpet-AutoCraftingTable
Cloth Config v9
Clumps
EntityCulling-Fabric
Fabric API
FastChest
Indium
Inventory HUD +
Iris
Item Scroller
LazyDFU
Litematica
Lithium
MaLiLib
MiniHUD
Mod Menu
oωo
Reese's Sodium Options
Replay Mod
Sodium
Sodium Extra
Starlight
Tweakeroo
WorldEdit
Xaero's Minimap
Xaero's Minimap

**Comment by jaredlll08** [comment]
I asked:
> Any other mods like Carpet or similar that messes with experience as well?

You said:

> And there shouldn't be any mods that messes with XP

Then you said you had these installed:

> Carpet Extra
> Carpet Mod
> Carpet TIS Addition
> Carpet-AutoCraftingTable

So yes, there are mods like ***CARPET*** that mess with experience.

Could be similar to https://github.com/jaredlll08/Clumps/issues/110#issuecomment-1334787845

Please check if `xpNoCooldown` is enabled.

**Comment by naecker21** [comment]
i didnt used any settings in carpet that messes with xp/ change things with xp

**Comment by jaredlll08** [comment]
Please upload your carpet config here

**Comment by naecker21** [comment]
Do you mean the file that's in the folder called carpet inside the config folder?

**Comment by naecker21** [comment]
For some reason the noxpcooldown is also enabled, but I don't believe that my XP is doubled. The XP I gained is nearly at the 32bit interval and there is no way to gain over one billion XP in 24hours and there is no way to gain this amount in the time I tested the farm.

**Comment by jaredlll08** [comment]
The bug I linked is not specifically duplicating the experience, the orb that player picked up just so happened to bug out and give them enough experience to appear as if it had doubled, I don't know the specifics of the bug, but I would be extremely surprised if it caused a straight up doubling of experience.

I'm going to close this issue since it is a bug with a feature of Carpet that Clumps already does, so there is no reason to have the carpet feature enabled, so disable the carpet feature and you shouldn't have issues.
