### ISSUE TITLE
Should I install Clumps if ServerCore (Can merge nearby exp orbs) installed?

### ISSUE THREAD

**Issue by HySand** [jaredlll08/Clumps#116]
Can I get extra effects from Clumps?

**Comment by jaredlll08** [comment]
Clumps just handles experience merging, nothing else, so if you have a mod that already does it, use that mod.

One thing to note, ServerCore only ups the chance that experience can merge, and only merges experience of the same value, whereas clumps merges all experience, so there will only ever be one orb in a certain radius.
