### ISSUE TITLE
Cap?

### ISSUE THREAD

**Issue by ZekePolarisBSH** [jaredlll08/Clumps#117]
Is there a cap on this thing? Even when 20 levels should be dropped, I only get 7... When picking up dropped XP

**Comment by jaredlll08** [comment]
There is no cap, you get ***EXACTLY*** the same amount of experience that you get in vanilla.
https://www.youtube.com/watch?v=_0Bo2yb63Eo

**Comment by ZekePolarisBSH** [comment]
Please don't close things before we get to read them. Makes you kinda sus... And I picked up 22 levels on vanilla before. That is mending video? Do you have a video on how much is received instead?

**Comment by jaredlll08** [comment]
The fact that the experience is used for mending doesn't matter, (*in vanilla and forge without any mods*) the XP to durability calculation is a deterministic function:
```java
    private int xpToDurability(int xp) {
        return xp * 2;
    }
```

Regardless, here is a new video showing that the experience is the same with clumps as it is with vanilla
https://www.youtube.com/watch?v=Oj7YbM4UW64

Just note that bottles of enchanting themselves are random, as dictated here:
https://minecraft.fandom.com/wiki/Bottle_o%27_Enchanting#Usage
> On impact, it drops experience orbs worth 3–11 (average 7.0)

So even though vanilla got slightly more experience in the video, if you had to run the test again (which is something you can do yourself if you think I'm "sus") it is possible that vanilla would get *less* experience than clumps.

**Comment by ZekePolarisBSH** [comment]
You not reading what I said shows I am right... Mending doesn't show how
much XP you get... Now there is a new issue with your mod.... It doesn't
clump at all anymore... I didn't change anything. No one used bottles.
Tested using players. Clearly you have no clue why I said sus...

**Comment by jaredlll08** [comment]
> You not reading what I said shows I am right... Mending doesn't show how
much XP you get...

And you're not reading what I'm saying, if I got `X` amount of mending on both clumps and vanilla, it means that I got `(X / 2)` experience on both, it just doesn't show it as a single value.

I'm not interested in arguing with you, If you want help, give me information like:
MC Version
Version of Clumps installed
Forge or Fabric
Single player or Server
(if server) Does the client have the mod installed as well
The latest.log file (from both server and client if applicable).

**Comment by ZekePolarisBSH** [comment]
I read what you said but you still don't understand why I was talking
about... If you can't understand that then you can't be trusted at all.
Again NO ONE SAID ANYTHING ABOUT BOTTLES THAT IS PROOF ENOUGH THAT YOU DO
NOT UNDERSTAND!!! Already reported you for harassment just because you
attacked me for not understand English, don't make me block you as well.

**Comment by ZekePolarisBSH** [comment]
I mean dude, grow up people are trying to sleep and you over here harassing
them by not reading what was said. As no one said bottles. So why even talk
about bottles?
