### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dexterdexterdex** [jaredlll08/Clumps#119]
the mod is simply doing nothing. im on a singleplayer world 1.19.4 and the mod does nothis with xp. there are still a ton of ex on the ground and they take minutes to pick up. the only mods in my mods folder are fabric api and clumps, both being the lates version 1.19.4

**Comment by jaredlll08** [comment]
Upload your latest.log file please

**Comment by dexterdexterdex** [comment]
[latest.log](https://github.com/jaredlll08/Clumps/files/11472389/latest.log)

**Comment by jaredlll08** [comment]
You don't have the mod installed.
There isn't a single instance of the world "clumps" in your log.
