### ISSUE TITLE
Make orbs always be combined together

### ISSUE THREAD

**Issue by roboderpy** [jaredlll08/Clumps#12]
https://github.com/jaredlll08/Clumps/blob/master/src/main/java/com/blamejared/clumps/entities/EntityXPOrbBig.java#L139

Replace check with `<=`

Otherwise Clumps entriely fail to fulfill it's purpose with mods installed which force players to use Clumps mod. (Example: Veinminer + JAOPCA Chunks + LargeVeins)

![2018-04-08_10 31 29](https://user-images.githubusercontent.com/6339511/38652802-bda2b98c-3e31-11e8-892c-89939c5add0c.png)

**Comment by jaredlll08** [comment]
I remember there being an edge case where the `<` vs `<=` mattered, but in my testing now, it doesn't seem to, will need to keep a lookout on it. (Changed in dev)
