### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by dexterdexterdex** [jaredlll08/Clumps#120]
the mod is simply doing nothing. im on a singleplayer world 1.19.4 and the mod does nothis with xp. there are still a ton of ex on the ground and they take minutes to pick up. the only mods in my mods folder are fabric api and clumps, both being the lates version 1.19.4. i hav ethe mod installed and it is in my  mods folder.
[latest.log](https://github.com/jaredlll08/Clumps/files/11478532/latest.log)
this is the log.

**Comment by jaredlll08** [comment]
Please don't make new issues, you can reply to that old issue.

The mod is NOT installed, the log file doesn't mention it at all, take a screenshot of your mods folder and upload it here.

**Comment by jaredlll08** [comment]
Also re-reading your issue:
> the only mods in my mods folder are fabric api and clumps

The log lists a whole lot more mods than just fabric api and clumps. you also have:
```
coordinatesdisplay
diggusmaximus
litematica
malilib
modmenu
optifabric
tweakeroo
```
So I'm not sure how you can only have clumps and fabric api in your mods folder if all of these are being loaded

**Comment by dexterdexterdex** [comment]
yes, i have more mods, i just said that bc i tested it with only those mods to see if other mods was the problem but they were not, im sorry for the confusion. here is my mods folder
![image](https://github.com/jaredlll08/Clumps/assets/133533472/02a14ac2-095a-4ee2-ba33-a14319d13f71)

**Comment by jaredlll08** [comment]
You have the `FORGE` version of Clumps, install the `FABRIC` version.
https://www.curseforge.com/minecraft/mc-mods/clumps/files/4444793
