### ISSUE TITLE
Fabric 1.20 support

### ISSUE THREAD

**Issue by kada49** [jaredlll08/Clumps#121]
Would it be possible to add support for Fabric 1.20? I already forked the project (since there is no 1.20 branch I didn't create a merge request) and changed what (I think) is necessary to make it work in Fabric 1.20. Note that in the settings.gradle.kts Forge is commented out, since it would throw an error when reloading the project atm.

(https://github.com/kada49/Clumps)

Would it also be possible to publish the mod releases to Modrinth too?

Thanks!

**Comment by jaredlll08** [comment]
I will be porting the mod in a few days after mojang has slowed down, they already put out a RC for 1.20.1.

As for modrinth:
https://modrinth.com/user/jaredlll08
