### ISSUE TITLE
XP orbs spawned from custom Spawn Eggs don't work

### ISSUE THREAD

**Issue by jhmaster2000** [jaredlll08/Clumps#124]
Testing in Singleplayer, using the following vanilla command:
`/give @s minecraft:bat_spawn_egg{EntityTag:{id:"minecraft:experience_orb",Count:65538,Value:32767s,CustomName:''}} 1`
You will get a bat egg which should spawn an XP orb giving thousands of levels.
**In Fabric, WITHOUT Clumps**: It works, the orb starts multiplying and spamming XP levels onto the player.
**In Fabric, INCLUDING Clumps**: The spawned XP orb from the egg gives no XP.

For comparison, the summon command:
`/summon experience_orb ~ ~ ~7 {Count:65538,Value:32767s,CustomName:''}`
...works both with or without Clumps.

Inspecting the egg-spawned XP orb from Clumps using `/data get` I noticed `Count` is intact, but `Value` is destroyed and set to zero.

**Versions:**
* Minecraft 1.20 (no, not 1.20.1)
* Fabric 0.14.21
* Clumps 11.0.0.1

**Comment by jaredlll08** [comment]
Should be working now, let me know if you run into any other issues
