### ISSUE TITLE
Clumps + LevelZ

### ISSUE THREAD

**Issue by le-off** [jaredlll08/Clumps#127]
Hello, in the modpack I use there is a mod called LevelZ that allows you to earn separate XP to level up in a skill tree. Is there a way to make Clumps work with the other XP orbs?

**Comment by jaredlll08** [comment]
Looking at their code, I don't see how they would benefit from support as they already appear to be using some of the clumps code.
https://github.com/Globox1997/LevelZ/blob/1.20/src/main/java/net/levelz/entity/LevelExperienceOrbEntity.java#L27-L28

**Comment by le-off** [comment]
Sorry, I didn't specify which version I'm playing on. I'm playing on 1.18.2 with LevelZ version 1.3.3. Is there a way to get Clumps to work with version 1.18.2 too?

**Comment by jaredlll08** [comment]
No.
Ask the LevelZ author if they will add support.
