### ISSUE TITLE
Sculk Catalysts not giving any XP

### ISSUE THREAD

**Issue by Vaskyy** [jaredlll08/Clumps#129]
Were using this mod on the server, and Sculk Catalysts dont work anymore.

I went in a SP world, works fine.
On server doesnt drop any XP anymore.

**Comment by jaredlll08** [comment]
Do the clients have Clumps installed?

**Comment by Vaskyy** [comment]
since its not told in the description: no
should it be?
```
Do I have to install it client or server side?
For 1.17 or newer versions it is only required on server side.
```
![Screenshot 2023-12-15 184713](https://github.com/jaredlll08/Clumps/assets/10385142/b1ea6f8b-2de1-4916-8a80-e5c92950572b)

**Comment by jaredlll08** [comment]
Please try install it on the client and see if you still experience the issue, it could be a desync.

**Comment by Vaskyy** [comment]
i did. no xp still.

**Comment by jaredlll08** [comment]
Do you have any other mods installed on the server?

**Comment by Vaskyy** [comment]
yes, but i dont know of any xp changes other than ur mod
do u know of any incompatibilities?

**Comment by Vaskyy** [comment]
Ok i found out what the "problem" was.
We have the **[Magnet Command-Mod](https://modrinth.com/mod/magnet-command)** installed, and when its on "OnBreak" setting then the xp orbs dont drop at all.
Has nothing to do with XP-Clumps :)
Thanks tho for trying to problemsolve with me 👍
