### ISSUE TITLE
add support for 1.20.3/1.20.4

### ISSUE THREAD

**Issue by dev-Younte** [jaredlll08/Clumps#130]

**Comment by Goofert42** [comment]
Yes please! Preferably 1.20.4. Don't rush it though.

**Comment by vlad8599** [comment]
Same! Add 1.20.4 support, pls.

**Comment by ArteeCool** [comment]
Please, add support for these versions

**Comment by jaredlll08** [comment]
1.20.3 is building https://github.com/jaredlll08/Clumps/commit/f90851d213cace19045829654981354f7b0b6da3

I will port to 1.20.4 after all my other mods are on 1.20.3

**Comment by SkyKingPX** [comment]
Thanks @jaredlll08

**Comment by Goofert42** [comment]
Nice!

**Comment by jaredlll08** [comment]
Sorry this took so long, but 1.20.4 is currently building
https://github.com/jaredlll08/Clumps/commit/77b2aaf1d70d174b126f9cd200955f2521513ae6
