### ISSUE TITLE
Crashes with latest version (13.0.0.5) on fabric

### ISSUE THREAD

**Issue by br14n-sol** [jaredlll08/Clumps#131]
It seems to crash when using the latest version in fabric, going back to the previous version (13.0.0.4) fixes it.

log file: [latest.log](https://github.com/jaredlll08/Clumps/files/13767233/latest.log)

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Clumps/commit/f04c393a7f60be57491ab35bb9d97b007fab36d1
