### ISSUE TITLE
Something going worry

### ISSUE THREAD

**Issue by FortyTwoCn** [jaredlll08/Clumps#132]
https://github.com/jaredlll08/Clumps/assets/112876033/2b54c73d-a460-4480-b418-40e1c390154a

1.16.5

**Comment by jaredlll08** [comment]
modlist?

Does this happen with just clumps installed?
Do you have any other mods that mess with experience?

**Comment by FortyTwoCn** [comment]
[modlist.txt](https://github.com/jaredlll08/Clumps/files/13896387/modlist.txt)
I suspect it's caused by multithreaded optimizations

**Comment by jaredlll08** [comment]
What mod does multithreaded optimizations?

You're going to need to uninstall optimization mods until it starts working, nothing in that list has known issues as far as I can tell.

**Comment by jaredlll08** [comment]
Closing due to no reply and no one else reporting similar.
