### ISSUE TITLE
Not collect 1.20.1 Forge

### ISSUE THREAD

**Issue by Krimatoria** [jaredlll08/Clumps#133]
Does not collect spheres of experience. Is it possible to increase the radius of collecting experience a little?
Clumps-forge-1.20.1-12.0.0.3.jar
![2024-03-02_17 55 12](https://github.com/jaredlll08/Clumps/assets/106809386/3ff7bc75-b147-4f0e-b7ad-88f5b563760c)
![2024-03-02_18 10 08](https://github.com/jaredlll08/Clumps/assets/106809386/29a32ce0-2236-4c8d-9b58-82efd1409c60)

**Comment by jaredlll08** [comment]
Do the orbs clump if they are closer together, or are they not clumping at all, no matter how close they are.

I am using the same distance that vanilla uses to combine the orbs, I'm not sure how I feel about doing a config option for it right now.

**Comment by jaredlll08** [comment]
Closing due to no reply and no one else reporting similar.
