### ISSUE TITLE
[1.20.4 Forge] Not working with XP Boost (Technical Enchant+ Datapack)

### ISSUE THREAD

**Issue by Sydrahh** [jaredlll08/Clumps#136]
Hey, good afternoon.
First of all, I'd like to thank you for your work. Found this mod several days ago and I added it to my little server right away.

Now, I'm having some sort of incompatibility with the XP Boost enchantment from the Technical Enchant+ datapack (as stated on the title). I'll provide all the details needed before I explain it:

Client version: 1.20.4
Clumps Version: 15.0.0.2
Forge Version: 49.0.38
Mod list:
balm-forge-1.20.4-9.0.6.jar
Clumps-forge-1.20.4-15.0.0.2.jar
InventoryProfilesNext-forge-1.20.2-1.10.9.jar
jei-1.20.4-forge-17.3.0.49.jar
kotlinforforge-4.10.0-all.jar
libIPN-forge-1.20.2-4.0.2.jar
offlineskins-1.20.4-v1.jar
trashslot-forge-1.20.4-16.0.1.jar
voicechat-forge-1.20.4-2.5.9.jar
Xaeros_Minimap_24.0.1_Forge_1.20.4.jar

Datapack link (just in case): [https://www.planetminecraft.com/data-pack/technical-enchant-for-1-17/](url)

As you can see, it's a not a heavily modded server. So, the problem is that without Clumps installed, the enchantment works just fine. You get several XP Orbs and level up way faster than usual (as intended). However, if it's installed, then it won't give the intended amount of XP. Like, the enchantment gets cancelled by the mod itself.

I have no idea why that happens. I've read that some had a similar issue with some mod that also had a boost thing (don't remember which one) and it was fixed apparently.

**Comment by jaredlll08** [comment]
Unfortunately due to how that datapack implements the feature, I don't think there is anything I can do on my side to fix this.
