### ISSUE TITLE
Build error on fresh clone

### ISSUE THREAD

**Issue by tmvkrpxl0** [jaredlll08/Clumps#137]
Hello, I cloned this repo and ran `./gradlew build` but the build failed with this error:
```
 Configure project :common
SpongePowered Vanilla 'GRADLE' Toolset Version '0.2.1-SNAPSHOT'

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/Clumps/common/build.gradle.kts' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'org.spongepowered.gradle.vanilla', version: '0.2.1-SNAPSHOT']
> Failed to apply plugin class 'org.spongepowered.gradle.vanilla.internal.ProvideMinecraftPlugin'.
   > Extension of type 'JavaToolchainService' does not exist. Currently registered extension types: [ExtraPropertiesExtension, MinecraftExtension]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 21s
```
I added this line to common/build.gradle.kts and it worked, perhaps you should look into this?
```diff
 plugins {
+    java
     id("org.spongepowered.gradle.vanilla") version "0.2.1-SNAPSHOT"
     id("com.blamejared.clumps.default")
 }
```

**Comment by jaredlll08** [comment]
That line already exists in the latest 1.20.4 branch.
Between the time I pushed the other branches and now, the VanillaGradle plugin has changed, requiring the java plugin to be applied before it.

Right now, I can't really justify spending time pushing it to older, non-mainted, branches without having a reason to do so (like working on the mod for those versions).

If you want to make a PR adding it, I would gladly accept it though.
