### ISSUE TITLE
increase version requirement on fabric to include 1.20.6

### ISSUE THREAD

**Issue by maximumpower55** [jaredlll08/Clumps#139]
1.20.6 is just a hotfix it should be supported without any code differences to 1.20.5, but the FMJ declares 1.20.5 only

**Comment by FearFreak** [comment]
2nd this!

Is there a workaround we can do ourselves to make fabric accept it? I hate not having this mod active! Thank you for the work you do keeping this mod up to date btw!

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Clumps/commit/0bc727c4345894322540c709889af89ba2492c69
