### ISSUE TITLE
Crash Report [1.12.2]

### ISSUE THREAD

**Issue by HeberonYT** [jaredlll08/Clumps#14]
Hello!
I have had a crash on my dedicated server.
I do not know how to replicate the problem, but some users already informed me that before crashing their base I had some orbs of xp. And it seems that the crasheo mentions something of the mod clumps.
Let me know if I am correct or should I inform someone in particular.
Thank you.

Minecraft 1.12.2
Modpack: FTB Revelation v2.5.0
Forge 14.23.4.2759
Clumps-3.1.1.jar
spongeforge-1.12.2-2705-7.1.0-BETA-3477.jar

Here is the report:
https://pastebin.com/raw/Wfb0JTiQ

**Comment by jaredlll08** [comment]
No idea on this, most likely an issue with sponge forge.
