### ISSUE TITLE
Lava not filling up Cauldrons. 

### ISSUE THREAD

**Issue by ItzDogo** [jaredlll08/Clumps#140]
Before I added this mod to the server Lava would fill up Cauldrons using Drip Stone, now they dont seem to be filling up at all. 

Mod Version: Clumps-forge-1.20.1-12.0.0.4.jar

**Comment by jaredlll08** [comment]
I can absolutely guarantee that this has absolutely nothing to do with my mod, I don't touch anything besides experience orbs.

**Comment by ItzDogo** [comment]
When I removed your mod the lava started working again. Before your mod the lava was working. Its your mod. I dont know how, but it is.

**Comment by jaredlll08** [comment]
At most, the only thing that could be happening is that by adding clumps, it changes the order that your other mods are loaded in, leading to this.


If you upload your latest.log file, I can take a look to see if anything stands out, but there is nothing I can change in my code, that is going to make cauldrons start working.

**Comment by ItzDogo** [comment]
https://mclo.gs/JZZFmyO

This is the only way to get logs from the server

**Comment by jaredlll08** [comment]
Nothing in there stands out to me as an obvious thing.

The only thing I can think of that you can do to solve this is:
Try run the server with no mods, see if dripstone works, it could be your server host disabling it.
If it does work, add clumps and see if it still works.
If clumps works (which it should), then slowly start adding mods back until it stops working, once it stops working, you know what mod caused it.

**Comment by ItzDogo** [comment]
It works without your mod though. The server has been up for a month without your mod and has worked.

**Comment by ItzDogo** [comment]
I removed Clumps and the lava started to work again. Its something to do with Clumps. Im not sure what, but it has to be 1 mod added stops working, 1 mod removed started to work.

**Comment by jaredlll08** [comment]
https://github.com/search?q=repo%3Ajaredlll08%2FClumps%20cauldron&type=code
https://github.com/search?q=repo%3Ajaredlll08%2FClumps+dripstone&type=code

There is nothing in my mod that touches anything besides experience orbs, I understand that it works fine without my mod, but at this point the only thing I could possibly do to fix your issue, is to make my experience orb mod, reimplement the dripstone mechanic in such a way that whatever other mod you have installed can't mess with it.

This is not related to my mod, there is nothing for my mod to do, there is no code that I can add to make dripstone magically start working.

You need to do what I suggested in my last comment, to figure out what mod is actually breaking this.
