### ISSUE TITLE
This mod contains a serious vulnerability in brushing experience

### ISSUE THREAD

**Issue by LitthoX** [jaredlll08/Clumps#141]
When many experience balls gather together, absorbing experience at this time will attract experience far greater than the original experience value! Thousands or tens of thousands of levels!

**Comment by jaredlll08** [comment]
What Minecraft version? 
What Clumps version
What Modloader?

**Comment by LitthoX** [comment]
1.12.2
3.0.0
forge

**Comment by jaredlll08** [comment]
Update to 3.1.2.
https://www.curseforge.com/minecraft/mc-mods/clumps/files/2666198
