### ISSUE TITLE
XP orbs become stuck in piston.

### ISSUE THREAD

**Issue by gksjohn** [jaredlll08/Clumps#142]
I have tested this mod alone server side and client side and it seems while XP orbs merge, they are unaffected by piston movement.

https://youtu.be/ers_pbyqdmI?si=E6fP8KkV599OF5ci

**Comment by jaredlll08** [comment]
What mc version?
What clumps version?
modloader and version?

**Comment by gksjohn** [comment]
> What mc version? What clumps version? modloader and version?

Sorry, I forgot to write any useful information. Raised this at 3am local lol.

MC Version: Minecraft 1.21
Clumps: 18.0.0.1
Modloader: Fabric Loader 0.15.11

The link I posted is an example farm where xp would clump near pistons and not move.

**Comment by jaredlll08** [comment]
Are you 100% sure that it is clumps causing this? Do you have any other mods and have you tested with just clumps?

Clumps doesn't do anything that would affect the movement of orbs

**Comment by gksjohn** [comment]
Sorry about the delay but it seems that as the orbs clump during movement, some can become stuck in blocks when clumping mid-movement. However, I am uncertain because this bug gets replicated more often in clumps than in vanilla.

**Comment by jaredlll08** [comment]
Just so I understand, the issue can be replicated in vanilla minecraft with no mods, just that using clumps it can be replicated more often / consistently?

**Comment by gksjohn** [comment]
Yes, that seems to be the case, I will close this issue as it doesn't seem like it's entirely a clumps issue.

**Comment by jaredlll08** [comment]
What is most likely the case here, is that the vanilla implementation of experience orb clumping is causing the issue, however, in vanilla, experience orbs of the same value have a 1 in 40 chance to clump together (iirc), but Clumps always clumps them together, which would make the issue happen way more often.
