### ISSUE TITLE
Villager XP not working correctly - 1.21

### ISSUE THREAD

**Issue by barthotymous** [jaredlll08/Clumps#145]
Having this issue on 1.21, I was playing 1.20 a few days ago and did not have this issue. I don't really know how to explain it well in words so I'm just gonna link the clip of it happening.

https://github.com/user-attachments/assets/02615040-e431-40fd-883c-261d9550201a

after a 5 - 10 seconds of what happens in the clip it stops happening and becomes one orb on the ground, but while it's doing it I can't do anything else like access shulker boxes

**Comment by jaredlll08** [comment]
What other mods are you using?

I highly doubt this is the clumps mod

**Comment by barthotymous** [comment]
I'm using a bunch but as I mentioned, it was working fine in 1.20 just recently. Is it a 1.21 thing?

**Comment by jaredlll08** [comment]
This is not a 1.21 thing as far as I am aware.

Saying you are using a bunch of mods is not helping, I want to know which mods you are using, to try and narrow down the issue.

I am testing this myself with just clumps, and I cannot reproduce your issue.

Can you reproduce this issue without clumps?

**Comment by barthotymous** [comment]
I was just checking, given that it's going to take a bit to write down all 50 or 60 mods I'm using lol

**Comment by barthotymous** [comment]
Appleskin
Architectury API
Better Beds
Better FPS
Better Thrid Person
Blur
Capes
Cherished Worlds
Cicada Lib
Cloth Config Api
Clumps
Configued 
Continuity
Cupboard
Custom FOV
Deepslate Instamine
Distant Horizons
Do a Barrel Roll
Easy Anvils
Effect Timer Plus
Enhanced Block Entities
Entity Model Features
Entity Texture Features
Entity Culling
Essential
Fabric API
Fabric Language Kotlin
Ferritecore
First Person Model
Forge Config API Port
Held Item Info
Hey Wiki
Immediately Fast
Indium
Invisible Frames
Iris
Itemscroller
Krypton
Litematica
Lithium
MaLiLib
Minihud
Modernfix
Mod Menu
Not Enough Animations
Notes
Paginated Advancements
Peek
Pick Up Notifier
Puzzles Lib
Reeses Sodium Options
Skin Layers 3D
Sodium
Sodium Extra
Sound Physics Remastered
Tweakeroo
Visuality
Yet Another Config Lib

**Comment by barthotymous** [comment]
Ah, would appear it happens without Clumps and thus not a Clumps issue, my apologies!
