### ISSUE TITLE
[Suggestion] Colored Clumps

### ISSUE THREAD

**Issue by Shadowclaimer** [jaredlll08/Clumps#17]
It would be great if we could config to change the color of XP in Clumps. I'm working on a modpack series and using a shared color as a thematic element and it'd be awesome to hue the clumps to match each one.

**Comment by jaredlll08** [comment]
In newer versions of Clumps we reuse the vanilla experience orb and the mod is server side only, not required on the client, so doing coloured orbs unfortunately is no longer feasible.
