### ISSUE TITLE
[1.14.3] Server crash on load on a dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [jaredlll08/Clumps#18]
Server crash - 
https://gist.github.com/ProsperCraft/a5afca8e9fcdbe0a2532eb32c3e591a6

[latest.log](https://github.com/jaredlll08/Clumps/files/3390780/latest.log)
[debug.log](https://github.com/jaredlll08/Clumps/files/3390781/debug.log)

Modpack - https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by jaredlll08** [comment]
Try with this version please.
https://www.curseforge.com/minecraft/mc-mods/clumps/files/2905428

**Comment by jaredlll08** [comment]
This has been fixed (tested on many servers)
