### ISSUE TITLE
Xp orbs randonly get stuck and server log is spammed with a warn

### ISSUE THREAD

**Issue by Poke5555** [jaredlll08/Clumps#19]
MC 1.14.3 | Clumps 4.0.0 | Forge 27.0.57

this is the warning
https://i.imgur.com/4VzdgNO.png 

and as for the xp orbs getting stuck, im not sure what causes it but we will see an xp orb it will float to us and nothing will happen until we break whatever block it was originally dropped on

**Comment by jaredlll08** [comment]
Try with this version please.
https://www.curseforge.com/minecraft/mc-mods/clumps/files/2905428

**Comment by jaredlll08** [comment]
No reply = probably fixed (also it was on forgecraft for a while without issue)
