### ISSUE TITLE
Server Lag with too much XP (Apotheosis)

### ISSUE THREAD

**Issue by littlett98** [jaredlll08/Clumps#22]
I'm currently using the mod Apotheosis which adds a lot of custom enchants with a much higher enchantment cap. Included in the mod is a way to make a huge amount of XP with a sword. When someone does this on the server it causes the server to lag behind and eventually crash due to ticks not being registered for over a minute. I'm not sure if it's a problem with the mod since I'm sure it works in Vanilla, but I thought I would mention that it may cause a lot of strain on the server when running XP mods.

**Comment by jaredlll08** [comment]
Not an issue with my mod, apotheosis should handle the huge amounts of XP better (as in don't spawn so much)
