### ISSUE TITLE
[1.14.4] Server hangs (crash because of the watchdog) when a chunk with many ExperienceOrbEntity is loaded.

### ISSUE THREAD

**Issue by HyCraftHD** [jaredlll08/Clumps#26]
Here is a thread dump when the server hangs:
https://gist.github.com/HyCraftHD/249805e85639182b68bdc45554664c94

The problem seems to be that in the EntityJoinWorldEvent the world is not ready to spawn a new entity:https://github.com/jaredlll08/Clumps/blob/ae81259102fcf393f300783ac3304124b6a9158f/src/main/java/com/blamejared/clumps/Clumps.java#L47

Might be related to #25

**Comment by jaredlll08** [comment]
Try with this version please.
https://www.curseforge.com/minecraft/mc-mods/clumps/files/2905428

**Comment by HyCraftHD** [comment]
Seems to be fixed thanks!
