### ISSUE TITLE
1.15 Game freezing after adding Clumps

### ISSUE THREAD

**Issue by Darkere** [jaredlll08/Clumps#27]
After adding Clumps to our pack existing worlds stop loading as the ServerThread locks up.

![image](https://user-images.githubusercontent.com/4283717/77225436-47e5b600-6b6f-11ea-9646-5ca80c911d06.png)

Clumps-5.0.1
profiling snapshot : [clumps lockup.zip](https://github.com/jaredlll08/Clumps/files/4362766/clumps.lockup.zip)

**Comment by Darkere** [comment]
just saw the update... gonna check that 

looking good gonna close once confirmed completely.

**Comment by jaredlll08** [comment]
Update to latest, I have already confirmed it works good on servers (I was getting this on ForgeCraft, I made a change and we haven't had any issues yet)
