### ISSUE TITLE
[1.14.4] Possible Server Crash? (Server Hangs Randomly.)

### ISSUE THREAD

**Issue by Gbergz** [jaredlll08/Clumps#31]
Title^

Forge: 28.2.4
MC: 1.14.4
Mod-Version: [Clumps](https://www.curseforge.com/minecraft/mc-mods/clumps/files/2905428)-**4.0.1**.jar

Crash-Report: [Gist Github](https://gist.github.com/Gbergz/aa49a39c5da2a894e28a86e8eac11cc9)

Any ideas?
- Gbergz

**Comment by jaredlll08** [comment]
Fixed in 1.15, 1.14 is no longer supported.
