### ISSUE TITLE
Huge ammount of XP orbs gathering and killing server + client

### ISSUE THREAD

**Issue by tjsd** [jaredlll08/Clumps#4]
Hello Jared!
In skyfactory v3.0.5 we suddenly have a large collection of com.blamejared.clumps.entities.EntityXPOrbBig floating around my base. Even if there is no where they could originate.

[20:06:02] [Server thread/INFO]: com.blamejared.clumps.entities.EntityXPOrbBig: 3101

http://imgur.com/a/0zhT1 screenshot

They are big and blue and keeps falling from the sky :) Like a 100 blocks over my base.

Server crash log: http://termbin.com/951t

/Sverd

**Comment by jaredlll08** [comment]
Hmm, do you have anything that is spawning XP orbs? like a mob farm or something?

Also what happens if you throw an experience bottle near the orbs?

**Comment by tjsd** [comment]
there is a mob farm close, but there is a vacuum hopper capturing all the xp.

Quetzi had a theory that it is an xp orb on a stair block trying to pathfind and that makes it all out of whack. And I have some chikckens closeto the stairs that I kill when I get better stats.

It sounds plausible to me and according to the crash report he said it looks like that is the case.

**Comment by jaredlll08** [comment]
hhm, interesting, what forge version?

**Comment by tjsd** [comment]
Forge Mod Loader version 12.18.3.2215 for Minecraft 1.10.2 loading

**Comment by jaredlll08** [comment]
ah ok that does explain why I was led to a dead end when looking at that trace, I'm builing on 2202, anyway I'll do some tests, but from what I can see, this should also affect vanilla XP orbs

Do you have any stair blocks around?

**Comment by tjsd** [comment]
yes, loads actually :)
Its an regular skyfactory 3.0.5 server with the forge version supplied. If thats not recommended maybe it should be mentioned to Darkosto.

**Comment by jaredlll08** [comment]
well no, I'm just building on an older forge, so I just need to update it my side, could you send me a picture of the stairs by chance? So I can try replicate it

**Comment by tjsd** [comment]
sure, no problem
imgur.com/a/siipI

there is an album, you can see the xp orbs bouncing everywhere, and I havent killed anything there at all since we cleared all the enteties last. I have been logged off in fact.

**Comment by jaredlll08** [comment]
Don't suppose You can get Q to install a custom clumps version to check if it is fixed?

**Comment by tjsd** [comment]
if you give me the link to the file I can test it in off hours tomorrow on the server.

**Comment by jaredlll08** [comment]
ok cool, so try this version
http://ss.blamejared.com/Clumps-1.0.3.jar
it *should* fix it, if not, it will help with the cleanup

**Comment by tjsd** [comment]
So I finally got time to test it with 1.0.3. It seems that removed the orbs or something but I still had 9 orbs floating around my base, just walking over them gave me level 100 from 0.

http://termbin.com/8twk

some of the output of fml-latest grepped with clumps

**Comment by jaredlll08** [comment]
ah ok, I left some debug output in, so this version made it a bit less restrictive for if orbs can clump together, so fixed?

**Comment by tjsd** [comment]
Im not convinced it the fixed the issue. The clumps were just gathering closer together yes. But why do they keep appearing and duping there?

**Comment by jaredlll08** [comment]
Well that may be because of a mod interaction, what Clumps actually does is, when an XP orb is spawned, it replaces it(https://github.com/jaredlll08/Clumps/blob/master/src/main/java/com/blamejared/clumps/events/CommonEventHandler.java#L16-L26), so I'm willing to bet that even without Clumps, there would still be XP orbs everywhere

**Comment by tjsd** [comment]
Yeah that could be, I just wish there was a way to clear all the orbs from console or something :) I cant play now since they are now back at over 3k orbs since I tried the new version yesterday and reverted.

**Comment by jaredlll08** [comment]
Hhm, I could work something in there, don't forget, the new version has to
be on client and server.

This is still a very weird thing, if it was a major issue (not only
affecting 1 server) then I'm sure darkosto would have told me about it :/

Tomorrow I'll make a version that will sort it out :)

**Comment by tjsd** [comment]
so there is a vanilla command to kill enteties.
I tried that :)
 /kill @e[type=item or entity]

So I did  /kill @e[type=EntityXPOrbBig]

That killed EVERY entity in the game..worms, players, sparks and orbs

**Comment by jaredlll08** [comment]
Wow, uh yea... That must be a vanilla bug, is anyone else on the server
having this issue?

Would it be possible for me to get access to the server with creative? So I
can fly around your base and see what is actually going on?

**Comment by tjsd** [comment]
Just ask Quetzi I guess? :)
http://termbin.com/7rez

**Comment by tjsd** [comment]
I've rebuilt my base now, removed the stairs and leveld it out, see if that helps :) let you know tomorrow!

**Comment by jaredlll08** [comment]
closing this because I never got feedback, also I made a change that made clumping entities more lenient
