### ISSUE TITLE
Problems with connect to forge server with Clumps installed

### ISSUE THREAD

**Issue by zTrap** [jaredlll08/Clumps#43]
**Clumps used:** 6.0.0.11, 6.0.0.10
**Client used:** Forge 1.16.3 34.1.17
**Server used:** Forge 1.16.3 34.1.17

Problem occurred only when I try to connect to forge server with forge client. I have tested some of clients and all works but forge.

![image](https://user-images.githubusercontent.com/18091396/95677350-873c2880-0bcd-11eb-809f-f7d8673c06b4.png)

Works:
 - Vanila (C) - Forge (S)
 - OptiFine (C) - Forge (S)

Not works:
 - Forge (C) - Forge (S)

Removing Your mod fixed this, but it's not a so solution I wanted to

**Comment by jaredlll08** [comment]
I'm super confused, is the mod on both the client and the server?

**Comment by zTrap** [comment]
Nope, it's only on server. Is it wrong?

**Comment by jaredlll08** [comment]
That is wrong. The mod is required on both the client and the server.

**Comment by zTrap** [comment]
Sorry, my bad 😓

**Comment by Pingger** [comment]
> 
> 
> That is wrong. The mod is required on both the client and the server.

why? I can't think of a single reason for this. It's not like you would need to register a new entity... Even the old craftbukkit server supported this serverside-only...

**Comment by jaredlll08** [comment]
>old craftbukkit 

This isn't old and this isn't craftbukkit

There may be a way to do this without an entity, but I do it with an entity and there haven't been any issues yet
