### ISSUE TITLE
Clumps possibly causing worlds to be frozen

### ISSUE THREAD

**Issue by BugmanBugman** [jaredlll08/Clumps#46]
Title. Sometimes, out of no where, my world gets locked in place and frozen. Looking at my console, it gets spammed with this: https://hatebin.com/bpbtzawgej
I'm not sure if it's definitey clumps, but I noticed that it was mentioned there so that's what i'm thinking. If it's not, directing towards the main culprit would be appreciated. Thanks!

**Comment by jaredlll08** [comment]
mc version?

**Comment by BugmanBugman** [comment]
1.16.4

**Comment by jaredlll08** [comment]
Okay...
What version of the Clumps then?

Could I also just get your full log on a paste please, since I should have fixed this ages ago.

**Comment by BugmanBugman** [comment]
Clumps-6.0.0.12
[debug.log](https://github.com/jaredlll08/Clumps/files/5544463/debug.log)
[latest.log](https://github.com/jaredlll08/Clumps/files/5544464/latest.log)

**Comment by BugmanBugman** [comment]
Oops, hatebin here for latest
https://hatebin.com/jhtzrmaebe

**Comment by jaredlll08** [comment]
remove MCMT and try again.

**Comment by BugmanBugman** [comment]
Yep, it sems to be MCMT causing this. Any idea why they conflict?

**Comment by jaredlll08** [comment]
The mod majorly changes how the game loop functions, which apparently breaks my simple iterator.

I'm honestly surprised that you haven't ran into more issues.

Report this incompatibility to them.
