### ISSUE TITLE
Mending not repairing multiple items at once

### ISSUE THREAD

**Issue by Enduriel** [jaredlll08/Clumps#49]
When having a lot of worn damaged armor and tools, the clumped xp will only repair one of them fully (it does seem to give a very tiny amount of xp to everything though). I realize that this has been discussed in #45 but it seems to have been forgotten and it would be good to have an open issue about it as this severely worsens the mending enchant.

**Comment by jaredlll08** [comment]
Fixed in d3c3fb10543e12f15a7e6ae8c257a3971f6e6c06
