### ISSUE TITLE
Biome Swapping?

### ISSUE THREAD

**Issue by countlessCritters** [jaredlll08/Clumps#50]
I run a Forge server. After a certain person created a _very_ productive creeper farm using Apotheosis, we decided to pick up this mod. As soon as we loaded into the server after restarting, though, the biomes were completely swapped. We found End biomes in the Overworld, Overworld biomes had been swapped as well, and Overworld biomes were in the End. This was the only mod we had picked up before restarting, though I'm well aware this could be a mod conflict, somehow. Anyway, we removed Clumps and restarted again, and the biomes were restored to their previous state.

**Comment by jaredlll08** [comment]
Is the mod installed on the client as well?

**Comment by jaredlll08** [comment]
Closing due to no reply in nearly 3 months and no one else has reported it.
