### ISSUE TITLE
[1.16.5]Server console error 

### ISSUE THREAD

**Issue by EnterFor** [jaredlll08/Clumps#51]
Forge：36.0.15
Mod：6.0.0.14

I'm Chinese, I can't read the code.
My friend suggested that I might have been clumps. Please help me.
Too fast spawn information server lag
Nothing strange happened in the game

https://paste.ubuntu.com/p/sw98KDCdng/

**Comment by jaredlll08** [comment]
Uninstall MCMT (https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading)
