### ISSUE TITLE
Tag 1.16.5 on CurseForge to enable custom profiles to add the mod

### ISSUE THREAD

**Issue by paulhlschr** [jaredlll08/Clumps#53]
**Question/Request**
Is it possible to tag Clumps on CurseForge with 1.16.5, as custom profiles and modpacks are not able to include the mod using the CurseForge client, if the profile runs on Forge 1.16.5?

**Comment by jaredlll08** [comment]
13bfd39f1be7670a5a72e53377e9c8923556df09
