### ISSUE TITLE
null crash log

### ISSUE THREAD

**Issue by Ki-Tan2934** [jaredlll08/Clumps#56]
Not sure what the problem is or how it is happening but maybe you have an idea
**Crash Log**
[https://paste.ubuntu.com/p/jcMX9tKn8T](url)
**Minecraft version** 1.16.5
**Forge version** forge-1.16.5-36.0.46.jar
**Clumps version** Clumps-6.0.0.17.jar
**Mod Pack** ATM6 version 1.5.4b

**Comment by jaredlll08** [comment]
Do you have performant or MCMT installed?

**Comment by Ki-Tan2934** [comment]
Performat is installed but 80% of the config options are disabled.

So only config not disabled are to do with mob spawning e.g. mob spawn
density.

And this has not been a problem for 5 months until now.

**Comment by jaredlll08** [comment]
/shrug 

Performant isn't supported.
https://github.com/jaredlll08/Clumps/issues/55
