### ISSUE TITLE
Clumps orbs cause a crash when colliding with "Advent of Ascension (Nevermine)" portals

### ISSUE THREAD

**Issue by ghost** [jaredlll08/Clumps#59]
**Mod Version**
I have tested the following combinations (on single and multiplayer)

1.15.2:
- Clumps (5.0.0 and 5.0.2.6)
- AoA (from 3.4.6 to 3.4.8)
- forge (31.2.48 and 31.2.50)

1.16.5 versions doesn't seems to be affected:
- Clumps 6.0.0.17
- AoA 3.5-beta-1
- forge 36.1.0

**Describe the bug**
When one or more experience orbs from the mod Clumps (entity type is clumps:xp_orb_big) collide with one of the AoA portals (entering the portals), a crash occurs immediately or in the next few seconds.
This issue is present with all the portals blocks and regardless of whether they are created through realmstones or picked and placed alone (creative inventory).
Here is a crash report: https://pastebin.com/tZ8Ga1xV (singleplayer)

**To Reproduce**
1. install:
    Forge 31.2.48
    Clumps-5.0.2.6
    AoA3-3.4.8
3. create or load a world in creative (just to reproduce faster, survival is affected too)
4. get a portal block from the search bar of the creative inventory / create a portal with realmstones
5. throw some bottles' o enchanting near/in the portals or drag an experience orb into the portal

**Screenshots**
The portal showed is the "Abyss Portal"
https://i.imgur.com/4x65v1h.png
https://i.imgur.com/w87dqqI.png
https://i.imgur.com/wGJHlAn.png

**Notes**
- An AoA nether portal causes a crash while a normal nether portal doesn't.
- It doesn't seems to matter the dimension in which the orb goes / comes from.
- I've tested with Minecraft original launcher and MultiMC.
- I haven't tried Forge 31.2.0 (recommended build) because AoA3-3.4.8 requires Forge 31.2.27
- **I've reported this issue to Advent of Ascension creators too.**

**Comment by jaredlll08** [comment]
I don't believe there is anything I can do on my side to fix this.

@Tslat if there is, then please let me know, but considering line numbers aren't matching your source, I am not sure where I would even start looking.

**Comment by Tslat** [comment]
Probably because he's on the 1.15.2 version, not the 1.16.5 version

This is the section we're looking at
![image](https://user-images.githubusercontent.com/7098525/116750668-26c7e800-aa46-11eb-9fbe-260beb776d58.png)

Is there any reason your entity would return null from a .create() call?

https://github.com/Tslat/Advent-Of-Ascension/blob/1.15.2/source/library/misc/AoATeleporter.java

**Comment by jaredlll08** [comment]
Well I guess now I know why my entity would return null from a .create call.

why does that method even exist.

**Comment by jaredlll08** [comment]
Closed in 0713c437a0f26fbe489ee425178ce85d248bb403
