### ISSUE TITLE
Tinkers' tools don't absorb this XP

### ISSUE THREAD

**Issue by MCEventHorizon** [jaredlll08/Clumps#6]
Having a tool in hand mending moss next to XP doesn't pick it up so the tools don't repair.

**Comment by jaredlll08** [comment]
What version of Clumps?

**Comment by MCEventHorizon** [comment]
I'm playing SkyFactory 3, version is 1.0.4

**Comment by jaredlll08** [comment]
I can't reproduce this, this is from my test world, no vanilla xp orbs have EVER existed in this world..
http://i.blamejared.com/iqELK.png

And the tool does get repaired, so I got no idea on this.
