### ISSUE TITLE
my mincraft client is  crashing when i join my server 

### ISSUE THREAD

**Issue by Grimoverlord** [jaredlll08/Clumps#62]
hi i have å problem with the Cumps mod. my mincraft client let me join the server for 1 mabye 2 min and then my mincraft client crashes 
and i was wornering if there are any ting i can do to fix it? please help  

[debug.log](https://github.com/jaredlll08/Clumps/files/6399320/debug.log)

**Comment by jaredlll08** [comment]
I need the latest.log file.

Please upload it to pasrebin.com

**Comment by Grimoverlord** [comment]
[latest.log](https://github.com/jaredlll08/Clumps/files/6399540/latest.log)

i dont know how to uplode files to pasrebin.com.   but here is the lastes.log from my mincraft client

**Comment by jaredlll08** [comment]
Your log doesn't mention Clumps at all, why do you think it is Clumps causing the issue?

**Comment by Grimoverlord** [comment]
because of the debug.log.  i was talking to with somone on the mincraft forge forum and got some help with my problem and he replied (  EntityXPOrbBig from the "clumps" mod is crashing. Talk to the mod author. )

**Comment by jaredlll08** [comment]
Link me where they said that please, since the debug log gives no info

**Comment by Grimoverlord** [comment]
https://forums.minecraftforge.net/topic/100172-server-player-crash-on-modded-server/

**Comment by Grimoverlord** [comment]
so you have any idea what i can do to make it work ?

**Comment by Grimoverlord** [comment]
i have downloaded the "patch" and i think it have fixed my problem.   i have been playing for one hour and no crash.

thank you so mutch for all your help :D
