### ISSUE TITLE
[issue] in the mods toml file do this.

### ISSUE THREAD

**Issue by BamsyTheSergal** [jaredlll08/Clumps#63]
please add a license to the mod in the newest version of the 1.16 curse forge mod. it doesnt load without it.

**Comment by jaredlll08** [comment]
Stop using the 1.15 file in 1.16.

The latest 1.16 file has it.

**Comment by BamsyTheSergal** [comment]
it did that with the 1.16 version of the file.

why would i download a 1.15 version when i intended it for 1.16.

**Comment by jaredlll08** [comment]
Is literally impossible.


https://github.com/jaredlll08/Clumps/blob/1.16/src/main/resources/META-INF/mods.toml#L4

What version of Clumps are you using?
