### ISSUE TITLE
1.16 version causes "missing license info" error

### ISSUE THREAD

**Issue by BileCantCode** [jaredlll08/Clumps#64]
Here is the log, seems to be an issue with mods made for 1.16. exact cause of the issue is, based on my research, nebulous and abstruse. Other mod users have had the same issue and fixed it via a method that no longer works.

[crash-2021-05-24_06.05.10-fml.txt](https://github.com/jaredlll08/Clumps/files/6531545/crash-2021-05-24_06.05.10-fml.txt)

**Comment by jaredlll08** [comment]
Stop using the 1.15 version on 1.16.
