### ISSUE TITLE
[Bug] Too much exp levels

### ISSUE THREAD

**Issue by Kim-Jong-Unn** [jaredlll08/Clumps#67]
Whenever I collect the clumped exp orbs it gives me a whole 1000 levels! It was only 3 zombies worth of exp clumps as well. This needs to be fixed asap.

**Comment by jaredlll08** [comment]
I need more info, Mc version? Clumps version?

**Comment by astemus** [comment]
MC 1.17
Fabric loader 0.11.3
Clumps version 7.0.0.1

**Comment by vhhawk** [comment]
Same issue, same versions. I was mining coal and suddenly shot up from 20 levels to 3758 and the game went wonky. 
Disclaimer. I'm running a total of 68 mods starting with the Better Minecraft modpack. One of those mods is the Diggus Maximus mod (veinminer type). All was well until boom.

**Comment by jaredlll08** [comment]
@vhhawk are you also using Fabric?

**Comment by jaredlll08** [comment]
Please can you guys try this version:
https://www.curseforge.com/minecraft/mc-mods/clumps/files/3352525

It should fix the issue.

**Comment by vhhawk** [comment]
> @vhhawk are you also using Fabric?

Yes, and thank you, I will load up and play the new version. Appreciate your quick work.

**Comment by jaredlll08** [comment]
Can anyone confirm if that new version fixed the issue?

**Comment by vhhawk** [comment]
I have played a few hours on the new version and have not encountered this issue since. Seems good to me.

**Comment by jaredlll08** [comment]
Perfect, considering this fixed then
