### ISSUE TITLE
Server Crash from XP Orbs

### ISSUE THREAD

**Issue by inctor** [jaredlll08/Clumps#7]
Hey,

So we just experienced a crash, that i'm not sure on how to recover from.

https://gist.github.com/inctor/bb969a4b644878e26f1d087fdcb6589b

The last thing I did, was left-clicking a Fluid/Item Conduit below an Absorption Hopper.
And the last thing the other player did was teleporting to our old base we haven't loaded in, for a while.

Any ideas?

**Comment by aelfwyne** [comment]
Having the same problem. I ran the tick profiler and it was the XP Orb Big lagging out my server. I had already extended the tick lagout time to over 15 minutes and it's still able to lag it badly enough to crash the server every few hours.

Have no idea where the offending orb(s) is/are at this moment. 

Started up the server with Clumps jar disabled and it spammed the screen with a few thousand "xp orb big" skipping entity messages, now the lag is down to a lot of normal XP Orbs... :/

**Comment by aelfwyne** [comment]
Still having server crashes myself from XP Orbs.... trying to figure it out. 

Clumps was supposed to help the issue but apparently it just delays it.

**Comment by jaredlll08** [comment]
Could I get an updated log for this please, line numbers are sadly wrong now :(

**Comment by TheVeyra** [comment]
Perhaps this one will help you?

https://gist.github.com/TheVeyra/9b78fad2dd589a8cfc8fba26d4770bb6

**Comment by jaredlll08** [comment]
Not really unfortunately, if possible I need one without sponge preferably

**Comment by jaredlll08** [comment]
I personally don't think this is an issue with clumps, so I'm going to close this, but please feel free to open another issue if you have any more crashes
