### ISSUE TITLE
Add fabric tag on CF

### ISSUE THREAD

**Issue by MenacingPerson** [jaredlll08/Clumps#71]
title

**Comment by jaredlll08** [comment]
![image](https://user-images.githubusercontent.com/5553605/127630326-061eb1d5-0a42-4b40-ab4e-d24806e969b6.png)

**Comment by MenacingPerson** [comment]
I'm talking about the categories, not the individual files

**Comment by jaredlll08** [comment]
Then just saying "title" isn't sufficient.

The mod is not a fabric mod.
The mod is for both Forge and Fabric, I just haven't had a chance to port to Forge 1.17 yet.

**Comment by MenacingPerson** [comment]
Yes but every mod that has/has had a fabric release or beta version has the fabric category.

**Comment by jaredlll08** [comment]
That is dumb.
I'm not adding the Fabric tag to my mod that originally (and still) uses Forge.
There isn't a Forge tag for me to add to it is there? (no. no there isn't.).

If you are searching for fabric mods, you should be using the "Game Version" drop down which lets you look for mods that actually have Fabric releases (and supports other modloaders like Forge / Rift).
Here is a direct link.
https://www.curseforge.com/minecraft/mc-mods?filter-game-version=2020709689%3A7499&filter-sort=4

Me wasting one of the categories to show duplicate data is dumb.
