### ISSUE TITLE
server or client side 

### ISSUE THREAD

**Issue by krispyking24** [jaredlll08/Clumps#72]
is it a server or client side mod or do they have to be on both

**Comment by jaredlll08** [comment]
1.17 is server side.
1.16 and down is required on both sides.

**Comment by krispyking24** [comment]
couldn’t u just remove the entity client side but it’s still there server side i have 0 coding knowledge so idek if that’s possible

**Comment by jaredlll08** [comment]
That isn't how it works.

I could make the 1.16 server side only, but I ***really*** do not want to rewrite the mod in 1.16.

**Comment by egeesin** [comment]
This info should be present in README.md or CurseForge description.
