### ISSUE TITLE
doesnt work with demagnetized mods

### ISSUE THREAD

**Issue by darkfang1989** [jaredlll08/Clumps#73]
doesnt work  with demagnetize, either of the demagnetize coil blocks of simple magnets, or the magnet insulator from tiered magnets. ran a couple tests and items dont pull once one of those are placed, but xp clumbs still pull despite a demagnetizer being placed and in range

**Comment by jaredlll08** [comment]
I'm unable to reproduce using the latest version of Clumps and Tiered Magnets on 1.16.5.

Make sure you haven't disabled XP magnets in their config.

**Comment by darkfang1989** [comment]
weird. i'll send a vid showing it but yea they're not disabled. i'd never do that XD

**Comment by darkfang1989** [comment]
https://youtu.be/kpvjlDfrs-U

architectury 1.18.26
clumps 6.0.0.17
ftb libary 1605.3.1
jei 7.7.1.121.448
mekanism generators 10.0.21.448
mekanism rotten flesh
mekanism tools 10.0.21.448
demagnetize 1.2.2

**Comment by jaredlll08** [comment]
I thought you said that it didn't work with the magnets themselves.

I looked at the code. 
Demagnetizer doesn't mention experience at all, so they don't support it, only items (I assume).
Tiered-Magnets insulator doesn't touch experience, only Items. Report that to them.
Simple-Magnets demagnetization coil doesn't touch experience, only Items. Report that to them.

Honestly this is the first time that I'm hearing of magnets touching experience, it isn't a common concept.
What I can assure you though, if a mod is touching experience and they are having issues with Clumps, then that is an issue with how the mod is detecting experience orbs, and there is literally nothing I can do to make Clumps work with them without them changing their code.
