### ISSUE TITLE
[Suggestion] Make the exponentiael xp bug a feature

### ISSUE THREAD

**Issue by TiphaineLAURENT** [jaredlll08/Clumps#76]
After playing a bit on the version containing this bug : https://github.com/jaredlll08/Clumps/issues/67, I find it very fun and would like to add a config flag to enable it.

**Comment by jaredlll08** [comment]
yea uh no, that very very very quickly hit the java max int and killed worlds.

Clumps is focused on combining orbs together, not changing how many orbs the player gets and it goes out of it's way to make sure that the player gets exactly what was clumped.

If you want this you will need a different mod.
