### ISSUE TITLE
"Clumps does not respect SemVer" in latest.log

### ISSUE THREAD

**Issue by ghost** [jaredlll08/Clumps#77]
From the latest.log [22:15:17] [main/WARN]: Mod `clumps` (fabric-1.17.1-7.0.5) does not respect SemVer - comparison support is limited.

The message occurs when loading game.
Minecraft 1.17.1
Fabric loader 0.11.6
Fabric API 40.0
Clumps-fabric-1.17.1-7.0.5

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Clumps/commit/1a4f65815bc2e8a13ed361b94ebe40e074042001
