### ISSUE TITLE
incompatibility symbol (red "x") in multiplayer menu

### ISSUE THREAD

**Issue by ghost** [jaredlll08/Clumps#83]
### To reproduce:
Ping a forge server in the multiplayer menu that does not have Clumps in its mods folder. The client will display a red "x" for incompatible even though you are able to join the server. Is this intended? Because I assumed CLumps is okay to run just client-side.

![redx](https://user-images.githubusercontent.com/82549089/135739924-284703ac-f615-447f-8269-032929c6dc94.JPG)

### Versions:
Forge 1.16.5-36,2,6
Clumps 6.0.0.26

### From clients latest.log:
_[02Oct2021 22:17:38.148] [Netty Client IO #3/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [clumps]_

**Comment by jaredlll08** [comment]
In 1.16, Clumps is required on both sides.
In 1.17 it is only required on the server. 

So 
> Because I assumed CLumps is okay to run just client-side.
Is a bad assumption.
