### ISSUE TITLE
Orb doesnt follow water flow like vanilla orb

### ISSUE THREAD

**Issue by GuillaumeOuint** [jaredlll08/Clumps#84]
Clumps entity doesnt follow water flow like vanilla orb do.
It break big XP shower that uses water to move orbs towards player.

I've installed this mod to reduce lag when XP shower is active, not to break it.

Clumps 6.0.0.26, Minecraft 1.16.5, Forge 36.2.2

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Clumps/commit/8d45918d7d95505d407ef2995cca3ffa8a2a1c14
