### ISSUE TITLE
Clumps causes the game to crash (fabric)

### ISSUE THREAD

**Issue by CapoFantasma97** [jaredlll08/Clumps#85]
Modpack with Fabric 0.12.5 for Minecraft 1.17.1

When Clumps is in the pack, it crashes the game with no crash log, only the regular logs. When removed, the pack works fine.

https://gist.github.com/CapoFantasma97/63a26f7cbefd352512c489d6d75a843f

**Comment by jaredlll08** [comment]
The issue is with Server-Core.

They are tracking it here:
https://github.com/Wesley1808/ServerCore-Fabric/issues/5
