### ISSUE TITLE
Can I use the clumps source code in 1.7.10 to make a mod?

### ISSUE THREAD

**Issue by Locu-akito** [jaredlll08/Clumps#87]
I found out about clumps on the web and wanted to use it, and when I tried to download it, I realized that I couldn't use it with other mods because I didn't have the 1.7.10 version, and since I'm making my own mods, I thought I could make a similar product to clumps, using the source code of clumps I asked if I could use the source code of clumps.

It would be great if you could return my reply.

I don't speak or write English, so I used the DeepL translation tool to write the text, so please understand that there may be some oddities.

Translated with www.DeepL.com/Translator (free version)

**Comment by jaredlll08** [comment]
The mod is licensed under the MIT license: https://github.com/jaredlll08/Clumps/blob/1.18/LICENSE.md

So I can't say no, you are free to use the code as you wish.

What I will say is, if you wanted to port the mod to 1.7.10, I could release a version on the CurseForge page for it, but I have no interest porting it myself.
