### ISSUE TITLE
Can you give me the source code for 1.12.2?

### ISSUE THREAD

**Issue by Locu-akito** [jaredlll08/Clumps#88]
Can I get the java source code for 1.12.2 Clumps? When I decompile the Clumps jar file, some of the programs are encrypted, and when I check them, some of the functions are different, so I was wondering if I could get the source code.

**Comment by jaredlll08** [comment]
https://github.com/jaredlll08/Clumps/tree/c607c2b4f761ee00686c1a54f15fa6044ff16abe
