### ISSUE TITLE
Why does my exp just vanish out of thin air when i kill a mob or use a bottle of enchanting?

### ISSUE THREAD

**Issue by Frizzledizzley** [jaredlll08/Clumps#89]
I don't know why this is happening, i use 1.16.5 forge and if you need to see my mods i'll show you.

**Comment by jaredlll08** [comment]
I need the mod list.

Can you reproduce with just Clumps?

**Comment by Frizzledizzley** [comment]
What do you mean by "reproduce?" https://gyazo.com/fe981ea37fa07d8a2b8b269f7a79a303
 Here are my mods btw.

**Comment by jaredlll08** [comment]
Do you have the issue with just clumps?

Also I need the latest.log

**Comment by Frizzledizzley** [comment]
I genuinely don't even know what the issue is, i just assumed it'd be clumps because it has to involve exp.

How do i find the latest log?

**Comment by jaredlll08** [comment]
> I genuinely don't even know what the issue is, i just assumed it'd be clumps because it has to involve exp.

I am asking you to remove all of your mods besides clumps, and tell me if the experience orbs are still disappearing.

> How do i find the latest log?

In the logs folder

**Comment by Frizzledizzley** [comment]
I'll see right now.

**Comment by Frizzledizzley** [comment]
[2021-12-03-2.log.gz](https://github.com/jaredlll08/Clumps/files/7654071/2021-12-03-2.log.gz)

**Comment by Frizzledizzley** [comment]
Ignore the name, its kinda goofy lol

**Comment by jaredlll08** [comment]
That log is from a crash, from what you have said, the game doesn't crash, the orbs just aren't appearing.

I need a log from a non crashing game where you used a bottle of enchanting

**Comment by Frizzledizzley** [comment]
Oh, okay. Sorry i just got confused.

**Comment by Frizzledizzley** [comment]
Im checking to see if the orbs disappear.

**Comment by Frizzledizzley** [comment]
Okay, it doesn't i'm gonna install mods one by one to see if they're the problem, thank you for your time.

The exp works i just don't know the problem but i will when i check out the mods. Cya.

**Comment by jaredlll08** [comment]
Start with removing Performant and https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks, both of those either have caused issues with Clumps in the past, or have their own Experience orb stuff

**Comment by Frizzledizzley** [comment]
Woah, thanks man!

**Comment by Frizzledizzley** [comment]
i didn't know that you can just reopen it, that caught me off guard. I'll begin that now.

**Comment by jaredlll08** [comment]
The issue still isn't with Clumps though, if those mods are breaking Clumps, they are doing something bad that needs fixing, there is not much I can or am willing to do on my side to fix them.

**Comment by Frizzledizzley** [comment]
well you've done enough to let me know that those are the problems, thank you so much and have a good day.
