### ISSUE TITLE
Remote hosted fabric server (0.12.8) crashes with Clumps

### ISSUE THREAD

**Issue by ReCrunch** [jaredlll08/Clumps#90]
I installed clumps on my server and it crashed on startup. After looking at closed issues I made sure the server was on version 12.8.
Here is the log https://paste.shockbyte.com/desofodanepagovikofa
I usually run the server with a few performance mods like lithium but for clarity I removed them on this startup.

Interestingly when I tried to create a server with clumps on my own pc it worked flawlessly. I have no idea why. The remote server keeps crashing however.

**Comment by jaredlll08** [comment]
What java version is the server running on?

Exact version and distribution please


I think if you try and re-install fabric from https://fabricmc.net/use/ on the server it will work

**Comment by ReCrunch** [comment]
Apparently it just works now. I tried to use the newest server again, as you said. I am even more confused now as I tried exactly that with the same server version and everything just 10 hours ago after I read the closed tickets and it did nothing. That's why I made the server on my own pc to begin with. 

Anyway thanks for your time and for making this mod.

**Comment by jaredlll08** [comment]
It seems to be something to do with Fabric, it doesn't think Java 17 is actually Java 17, while I could fix it on my side by asking for Java 16 (Even though I'm building on Java17...), I feel that is going to cause issues in the future.
