### ISSUE TITLE
xp orbs merging lose their velocity

### ISSUE THREAD

**Issue by jbreckel** [jaredlll08/Clumps#92]
Not sure if it has been reported or fixed in a newer version.

MC: `1.16.5`
Forge: `36.2.23`
Clums: `6.0.0.27`
[modpack: vault-hunters: `1.12.4`]

I built illmangos gold farm. [youtube](https://www.youtube.com/watch?v=lCs3StdbuqU)

One point of this farm is, to separate items from xp and letting the xp travel through an elevator up to the player.
xp travel over packed ice.

the vanilla xp orbs behave in that they keep their velocity and arrive at the player on top of the elevator.

with clumps, the xp merge into balls on the ice paths and just stay there.

not sure if this has something to do, with the merging slowing the orbs down, or if their velocity is not taken into account.

Is this something that could be fixed?

My Java skills are very rusty, but I could submit a PR if this is actually something worth your time.

Thanks for this awesome mod.

**Comment by AmcUhrd** [comment]
Yes. Running into the exact same problem on the 1.16.5 version!! I deleted this mod to see if it helped and its defintly this mod that breaks the farm

**Comment by jaredlll08** [comment]
Just pushed a possible fix for this, please test that and let me know if it works

**Comment by AmcUhrd** [comment]
I have no idea how to do that to honostly

**Comment by jaredlll08** [comment]
https://www.curseforge.com/minecraft/mc-mods/clumps/files/3658432

**Comment by AmcUhrd** [comment]
tnx trying it now!

**Comment by AmcUhrd** [comment]
after running the farm for 5 minutes it seems to run flawelesly now. Thank you so very much!!!

**Comment by quietust** [comment]
For what it's worth, I just ran into literally the exact same problem (same gold farm, same modpack). The above update does help a lot, but I still occasionally see XP orbs getting stuck in the middle of the ice channels - it appears that when two XP orbs merge, the result becomes *larger* in size, and if that larger XP orb ends up inside a block, it stops moving (and any orbs that merge into it _also_ stop moving).

**Comment by jaredlll08** [comment]
I don't see anything in my code or the vanilla code that makes orbs larger, all orbs should have a size of `0.5 x 0.5` regardless of how much experience is stored, so if they are getting larger, then you may have another mod messing with it.
