### ISSUE TITLE
Help. GL ERRORS which probably cause freezing in minecraft Forge 1.16.5

### ISSUE THREAD

**Issue by HarperV** [jaredlll08/Clumps#95]
I noticed in my latest log file such errors 
![image](https://user-images.githubusercontent.com/103311577/162566506-bad69ecd-0b8b-48f7-befc-d4ec8ca2aae6.png)
Came to a conclusion that they coincides with the momets the game freezes when I render chunks on my map. It happens every time on the same chunks. 
What does this error mean and how I can fix it?
Mods: 
![image](https://user-images.githubusercontent.com/103311577/162566638-359b9d73-3140-485f-8458-cf8714dd197e.png)

**Comment by jaredlll08** [comment]
You don't even have Clumps installed, so whatever the issue is, it isn't anything I can solve.
