### ISSUE TITLE
Random crash that seems to be cause by Clumps 

### ISSUE THREAD

**Issue by Smokedeuch** [jaredlll08/Clumps#96]
[crash-2022-05-08_17.05.52-server.txt](https://github.com/jaredlll08/Clumps/files/8647876/crash-2022-05-08_17.05.52-server.txt)

**Comment by jaredlll08** [comment]
Why do you think this is related to clumps?

**Comment by jaredlll08** [comment]
Closing due to no reply (also there is nothing in that log that points to clumps)
