### ISSUE TITLE
Apotheosis low xp count

### ISSUE THREAD

**Issue by Nyntex** [jaredlll08/Clumps#97]
I am using the mod Apotheosis that has enchantments to increase the xp gained from killing mobs. But with Clumps all of that is getting destroyed and i only receive the low xp counts from killing Mobs. For better understanding: in Apotheosis there is an enchantment to swap out dropped items for raw xp, 25 xp per item * the enchantment level to be exact.
Clumps just straight up deletes all of the xp I would have gained from the converted items. 
I hope it`s an easy fix.

Clumps-forge-1.18.2-8.0.0+8

Forge-40.1.20

Edit: so even reinstalling the mod I see the same picture. One orb giving like 0 XP and sometimes a orb that gives a little more. It is really inconsistent. Clumps is the only mod i removed and it works perfectly fine so i really don`t know what else could be the problem. It's also weird that it works for you just fine....

**Comment by jaredlll08** [comment]
Clumps doesn't change anything about experience besides how it merges and how it gives that experience to players.

This video shows that on both vanilla and clumps, you get the same amount of experience (give or take normal experience randomness)
https://www.youtube.com/watch?v=_0Bo2yb63Eo

With apotheosis with looting and knowledge applied, I am unable to reproduce this issue, you may have other mods causing issues.
https://user-images.githubusercontent.com/5553605/169662706-ecf0920a-bd00-468b-a2a8-b904eb9b7b43.mp4
