### ISSUE TITLE
Add the mod to Modrinth

### ISSUE THREAD

**Issue by TechPro424** [jaredlll08/Clumps#98]
A request to add the mod to the Modrinth platform: https://modrinth.com/

**Comment by jaredlll08** [comment]
I currently have no interest in my mods being uploaded to Modrinth.

My files are already available to third parties via the CurseForge API.

**Comment by Sammcb** [comment]
Would love to see this on Modrinth too as they have a very accessible API.

**Comment by jaredlll08** [comment]
https://modrinth.com/user/jaredlll08
