### ISSUE TITLE
Clumped orbs processed outside of Clumps will not give the correct experience amount

### ISSUE THREAD

**Issue by enigmaquip** [jaredlll08/Clumps#99]
If an orb is picked up from in world, or processed during the forge pickupXp event causing a cancel, then the method processing that orb will not have the proper info about that orb. Only Count seems to be updated on merges, whichever orb wins just keeps it's value.
From my looking around, most mods are pulling just the value of the orb.
![image](https://user-images.githubusercontent.com/6134440/173691427-62c9d411-efd8-4143-8397-36f3e16e6874.png)
In the above example, with a combined 18,134xp, mods would see it as 1xp
 

This also relates back to #97

**Comment by jaredlll08** [comment]
What mc version?

**Comment by enigmaquip** [comment]
1.18.2

**Comment by enigmaquip** [comment]
Working great. Thanks for all the hard work!
